### ISSUE TITLE
Add more graceful loading indicators

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/about#33]
Two locations:

1) The side panel, after hitting save for the markdown
2) The landing page, in the widget region

We should use the aragonUI components with the spinner.

Note that it remains stuck on this screen and doesn't try to fetch the file

![image](https://user-images.githubusercontent.com/2584493/61742144-baa95200-ad92-11e9-88d9-d3d712cd9b2d.png)

**Comment by stellarmagnet** [comment]
Does this issue still exist, @ottodevs ? If not, please close. Otherwise let's make sure it's addressed in the current sprint.

**Comment by ottodevs** [comment]
Short update: The text on the screenshot was already removed, at most we should ensure the loading indicators used are consistent with other Aragon apps and the general design guidelines

**Comment by stellarmagnet** [comment]
Closing this issue, not an issue anymore!
